### ISSUE TITLE
database_does_not_exist error when doing general deployment

### ISSUE THREAD

**Issue by NeillGiraldo** [UNArqui17i-B/API-getway#10]
when I run:
 ```
    docker-compose build
    docker-compose up
```

and try to create account I get this error either general or user_compose.yml

**Comment by maasencioh** [comment]
@NeillGiraldo could you please take a screenshot or paste the whole exception and from which microservice is from

**Comment by NeillGiraldo** [comment]
When I try this http request:

`
   GET  http://192.168.99.101:5000/api/users/
`
I get this error

`
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Error: Not Found
            <br> &nbsp; &nbsp;at /git/api-gateway/src/index.js:37:15
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/git/api-gateway/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/git/api-gateway/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /git/api-gateway/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/git/api-gateway/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/git/api-gateway/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at /git/api-gateway/node_modules/express/lib/router/index.js:635:15
            <br> &nbsp; &nbsp;at next (/git/api-gateway/node_modules/express/lib/router/index.js:260:14)
            <br> &nbsp; &nbsp;at Function.handle (/git/api-gateway/node_modules/express/lib/router/index.js:174:3)
            <br> &nbsp; &nbsp;at router (/git/api-gateway/node_modules/express/lib/router/index.js:47:12)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/git/api-gateway/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/git/api-gateway/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /git/api-gateway/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/git/api-gateway/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/git/api-gateway/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at /git/api-gateway/src/index.js:27:6
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/git/api-gateway/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/git/api-gateway/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /git/api-gateway/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/git/api-gateway/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/git/api-gateway/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at next (/git/api-gateway/node_modules/express/lib/router/route.js:127:14)
        </pre>
    </body>
</html>`
`
and I get this on rancher-server

`
RASH REPORT Process chttpd_auth_cache with 0 neighbours exited with reason: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,325}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,313}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,329}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,184}]},...]} in gen_server:terminate/6 line 737
4/23/2017 10:07:51 PM03:07:51.964 [error] Supervisor chttpd_sup had child chttpd_auth_cache started with chttpd_auth_cache:start_link() at <0.6588.0> exit with reason {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,325}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,313}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,329}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,184}]},...]} in context child_terminated
4/23/2017 10:07:56 PM03:07:56.967 [error] gen_server chttpd_auth_cache terminated with reason: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,325}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,313}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,329}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,184}]},...]}
`
and the weirdest thing is that database does exists and is running....

**Comment by NeillGiraldo** [comment]
Database connection is ok.

when I try this directly to the microservice it performs ok

`http://192.168.99.101:4000/users`
