### ISSUE TITLE
login: add user

### ISSUE THREAD

**Issue by maasencioh** [UNArqui17i-B/API-getway#5]
If the login is successful, return the user

**Comment by NeillGiraldo** [comment]
Frontend side done - https://github.com/UNArqui17i-B/FrontEnd/commit/d78fff24d0d5f46084fab4c6815286c224db9f65

**Comment by maasencioh** [comment]
Added in https://github.com/UNArqui17i-B/Authentication/commit/a80ff66cbe0d00bea895ec1e406fedcdc2c4f1fe

Please test it in front @NeillGiraldo
